apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploytest
  name: deploytest
  namespace: wave2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploytest
  strategy: {}
  template:
    metadata:
      labels:
        app: deploytest
    spec:
      containers:
      - image: nginx
        name: nginx
